checkpoints:
  checkpoint_interval: 1000
  checkpoints_path: checkpoints_dsv3_debug
  checkpoints_path_is_shared_file_system: false
  load_lr_scheduler: true
  load_optimizer: true
  resume_checkpoint_path: null
  save_final_state: true
  save_initial_state: false
data_stages:
- data:
    dataset:
      dataset_overwrite_cache: false
      dataset_processing_num_proc_per_process: 4
      hf_dataset_config_name: null
      hf_dataset_or_datasets: BEE-spoke-data/TxT360-1M-sample
      hf_dataset_splits: train
      text_column_name: text
    num_loading_workers: 4
    seed: 444
  name: Stable Training Stage
  start_training_step: 1
general:
  benchmark_csv_path: null
  consumed_train_samples: null
  ignore_sanity_checks: true
  project: dsv3_test
  run: dsv3_test_debug
  seed: 444
  step: null
lighteval: null
logging:
  iteration_step_info_interval: 1
  log_level: info
  log_level_replica: info
model:
  ddp_bucket_cap_mb: 25
  dtype: bfloat16
  init_method:
    std: 0.02
  make_vocab_size_divisible_by: 1
  model_config:
    bos_token_id: 128000
    eos_token_id: 128009
    hidden_act: silu
    hidden_size: 1024
    initializer_range: 0.02
    intermediate_size: 2048
    is_deepseekv3_config: true
    seq_len: 512
    original_seq_len: 512
    num_attention_heads: 16
    num_hidden_layers: 12
    num_key_value_heads: 16
    pad_token_id: null
    rms_norm_eps: 1.0e-05
    tie_word_embeddings: true
    use_cache: false
    vocab_size: 128256
    max_batch_size: 8
    n_dense_layers: 1
    n_routed_experts: 6
    n_shared_experts: 2
    n_activated_experts: 4
    n_expert_groups: 1
    n_limited_groups: 1
    score_func: sigmoid
    route_scale: 1.0
    moe_intermediate_size: 256
    q_lora_rank: 256
    kv_lora_rank: 256
    qk_nope_head_dim: 96
    qk_rope_head_dim: 32
    v_head_dim: 128
    rope_theta: 10000.0
    rope_factor: 1.0
    beta_fast: 32
    beta_slow: 1
    mscale: 1.0
    rope_scaling: null
    rope_interleaved: false
optimizer:
  accumulate_grad_in_fp32: true
  clip_grad: 1.0
  learning_rate_scheduler:
    learning_rate: 3.0e-4
    lr_decay_starting_step: 50
    lr_decay_steps: 950
    lr_decay_style: cosine
    lr_warmup_steps: 50
    lr_warmup_style: linear
    min_decay_lr: 3.0e-5
  optimizer_factory:
    adam_beta1: 0.9
    adam_beta2: 0.95
    adam_eps: 1.0e-08
    name: adamW
    torch_adam_is_fused: true
  weight_decay: 0.01
  zero_stage: 0
parallelism:
  dp: 1
  expert_parallel_size: 1
  pp: 1
  pp_engine: 1f1b
  recompute_layer: false
  tp: 1
  tp_linear_async_communication: true
  tp_mode: REDUCE_SCATTER
  tp_recompute_allgather: true
profiler: null
tokenizer:
  tokenizer_max_length: null
  tokenizer_name_or_path: unsloth/Llama-3.2-1B-Instruct
  tokenizer_revision: null
tokens:
  batch_accumulation_per_replica: 2
  limit_test_batches: 0
  limit_val_batches: 0
  micro_batch_size: 2
  sequence_length: 512
  train_steps: 1000
  val_check_interval: -1
