checkpoints:
  checkpoint_interval: 1000
  checkpoints_path: checkpoints_vellichor_full_1e-5
  checkpoints_path_is_shared_file_system: false
  load_lr_scheduler: true
  load_optimizer: true
  resume_checkpoint_path: null
  save_final_state: false
  save_initial_state: false
data_stages:
- data:
    dataset:
      dataset_overwrite_cache: false
      dataset_processing_num_proc_per_process: 1
      hf_dataset_config_name: null
      hf_dataset_or_datasets: BEE-spoke-data/TxT360-1M-sample
      hf_dataset_splits: train
      text_column_name: text
    num_loading_workers: 24
    seed: 42
  name: Stable Training Stage
  start_training_step: 1
general:
  benchmark_csv_path: null
  consumed_train_samples: null
  ignore_sanity_checks: true
  project: vellichor_sweeps
  run: vellichor_full_1e-5
  seed: 42
  step: null
lighteval: null
logging:
  iteration_step_info_interval: 1
  log_level: info
  log_level_replica: info
model:
  ddp_bucket_cap_mb: 25
  dtype: bfloat16
  init_method:
    std: 0.02
  make_vocab_size_divisible_by: 1
  model_config:
    bos_token_id: 128000
    eos_token_id: 128009
    hidden_act: silu
    hidden_size: 960
    initializer_range: 0.02
    intermediate_size: 2560
    is_vellichor_config: true
    max_position_embeddings: 2048
    num_attention_heads: 24
    num_hidden_layers: 32
    num_key_value_heads: 24
    pad_token_id: null
    pretraining_tp: 1
    rms_norm_eps: 1.0e-05
    rope_interleaved: false
    rope_scaling: null
    rope_theta: 10000.0
    tie_word_embeddings: true
    use_cache: true
    vocab_size: 128256
    use_qk_norm: true
    q_lora_rank: 256
    kv_lora_rank: 256
    qk_nope_head_dim: 96
    qk_rope_head_dim: 32
    v_head_dim: 128
    linear_attn_head_dim: 120
    linear_attn_num_heads: 6
    full_attention_every_n_layers: 1
optimizer:
  accumulate_grad_in_fp32: true
  clip_grad: 1.0
  learning_rate_scheduler:
    learning_rate: 1.0e-5
    lr_decay_starting_step: 200
    lr_decay_steps: 9800
    lr_decay_style: cosine
    lr_warmup_steps: 200
    lr_warmup_style: linear
    min_decay_lr: 1.0e-6
  optimizer_factory:
    adam_beta1: 0.9
    adam_beta2: 0.95
    adam_eps: 1.0e-08
    name: adamW
    torch_adam_is_fused: true
  weight_decay: 0.01
  zero_stage: 0
parallelism:
  dp: 8
  expert_parallel_size: 1
  pp: 1
  pp_engine: 1f1b
  recompute_layer: false
  tp: 1
  tp_linear_async_communication: true
  tp_mode: REDUCE_SCATTER
  tp_recompute_allgather: true
profiler: null
s3_upload: null
tokenizer:
  tokenizer_max_length: null
  tokenizer_name_or_path: unsloth/Llama-3.2-1B-Instruct
  tokenizer_revision: null
tokens:
  batch_accumulation_per_replica: 4
  limit_test_batches: 0
  limit_val_batches: 0
  micro_batch_size: 8
  sequence_length: 2048
  train_steps: 10000
  val_check_interval: -1
